dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t $DOCKER_USERNAME/pyiron-alpine .
      - docker images
      - docker push $DOCKER_USERNAME/pyiron-alpine
    - stage: test
      script: docker run --rm $DOCKER_USERNAME/pyiron-alpine echo hello world
    - script: docker run --rm $DOCKER_USERNAME/pyiron-alpine echo hello world
